/* Anesthculator v0.73.0 Hybrid — workflow prototype only */
const STORAGE_KEY='anesth-v0731-senior-mentor';
const CAUSES={
 vasodilation:{name:'Vasodilation / anesthetic effect',base:44},
 hemorrhage:{name:'Hemorrhage / hypovolemia',base:34},
 arrhythmia:{name:'Pump failure / arrhythmia',base:22},
 obstruction:{name:'Obstructive cause',base:14},
 anaphylaxis:{name:'Anaphylaxis',base:12}
};
const ACTIONS=['Call for help','Verify BP / waveform','Optimize oxygenation & ventilation','Reduce reversible anesthetic effect'];
const QUESTIONS=[
{id:'bleeding',label:'Active bleeding',text:'มองที่ surgical field: มี active bleeding หรือ major volume loss หรือไม่?',why:'แยก hemorrhage/hypovolemia ออกจาก vasodilation ซึ่งเป็นสองสาเหตุที่ต้องจัดการต่างกัน',opts:['yes','no','unknown'],gain:95,w:{yes:{hemorrhage:52},no:{hemorrhage:-24,vasodilation:7},unknown:{}}},
{id:'ppv',label:'PPV / dynamic preload',text:'PPV หรือ dynamic preload indicator เป็นอย่างไร?',why:'ช่วยประเมิน preload responsiveness เมื่อเงื่อนไขการวัดเหมาะสม',opts:['high','normal/low','unreliable','unknown'],gain:82,w:{high:{hemorrhage:28},'normal/low':{hemorrhage:-8,vasodilation:8},unreliable:{},unknown:{}}},
{id:'rash',label:'Allergic signs',text:'มี rash, flushing, angioedema หรือ sudden bronchospasm หรือไม่?',why:'ต้องรีบคัดกรอง anaphylaxis ซึ่งอาจทรุดเร็วและเปลี่ยนการรักษาทันที',opts:['yes','no','unknown'],gain:90,w:{yes:{anaphylaxis:62},no:{anaphylaxis:-20},unknown:{}}},
{id:'airway',label:'Airway pressure',text:'Peak airway pressure เพิ่มขึ้นอย่างฉับพลันหรือไม่?',why:'ช่วยแยก bronchospasm/anaphylaxis และ obstructive physiology',opts:['yes','no','unknown'],gain:65,w:{yes:{anaphylaxis:18,obstruction:18},no:{anaphylaxis:-5,obstruction:-7},unknown:{}}},
{id:'rhythmChange',label:'Rhythm / HR change',text:'มี new major rhythm หรือ heart-rate change หรือไม่?',why:'ถ้าเป็น pump failure ต้องรู้ rhythm ก่อนเข้าสู่ algorithm ที่เหมาะสม',opts:['yes','no','unknown'],gain:88,w:{yes:{arrhythmia:38},no:{arrhythmia:-13},unknown:{}}},
{id:'rhythmType',label:'Rhythm type',text:'Rhythm ปัจจุบันคืออะไร?',why:'ชนิด rhythm เป็นตัวกำหนด treatment branch และความเร่งด่วน',opts:['AF','sinus tachycardia','SVT regular','VT/VF','bradyarrhythmia','uncertain'],gain:100,show:s=>s.answers.rhythmChange==='yes',w:{AF:{arrhythmia:28},'sinus tachycardia':{hemorrhage:8,vasodilation:5},'SVT regular':{arrhythmia:32},'VT/VF':{arrhythmia:60},bradyarrhythmia:{arrhythmia:42},uncertain:{}}},
{id:'afOnset',label:'AF onset',text:'AF นี้เป็น new onset หรือ pre-existing?',why:'Onset ช่วยกำหนด trigger search, rhythm strategy และความเร่งด่วนของการประเมินสาเหตุ',opts:['new onset','pre-existing','unknown'],gain:92,show:s=>s.answers.rhythmType==='AF',w:{'new onset':{arrhythmia:8},'pre-existing':{arrhythmia:2},unknown:{}}},
{id:'afStability',label:'AF stability',text:'ผู้ป่วย hemodynamically unstable เพราะ AF หรือไม่?',why:'แยก synchronized cardioversion pathway จากการแก้ trigger/rate control',opts:['unstable','stable','uncertain'],gain:100,show:s=>s.answers.rhythmType==='AF',w:{unstable:{arrhythmia:20},stable:{arrhythmia:-2},uncertain:{}}},
{id:'afRate',label:'Ventricular rate',text:'Ventricular rate โดยประมาณเท่าไร?',why:'ช่วยประเมินว่า rapid ventricular response มีผลต่อ perfusion มากเพียงใด',opts:['<110','110–150','>150','uncertain'],gain:80,show:s=>s.answers.rhythmType==='AF',w:{'<110':{arrhythmia:-5},'110–150':{arrhythmia:9},'>150':{arrhythmia:20},uncertain:{}}},

{id:'afTrigger',label:'Likely AF trigger',text:'มี reversible trigger ใดเด่นที่สุดในตอนนี้?',why:'Perioperative AF มักเป็น marker ของปัญหาอื่น การแก้ trigger อาจสำคัญกว่าการลด rate เพียงอย่างเดียว',opts:['hypovolemia/bleeding','pain/light anesthesia','hypoxia/hypercarbia','electrolyte/metabolic','ischemia/pump problem','uncertain'],gain:86,show:s=>s.answers.rhythmType==='AF'&&!!s.answers.afRate,w:{'hypovolemia/bleeding':{hemorrhage:18},'pain/light anesthesia':{vasodilation:-4},'hypoxia/hypercarbia':{arrhythmia:6,obstruction:8},'electrolyte/metabolic':{arrhythmia:10},'ischemia/pump problem':{arrhythmia:18},uncertain:{}}},
{id:'etco2',label:'Abrupt ETCO₂ fall',text:'ETCO₂ ลดลงฉับพลันโดยไม่มี ventilation explanation หรือไม่?',why:'เป็นสัญญาณสำคัญของ abrupt fall in pulmonary blood flow/cardiac output',opts:['yes','no','unknown'],gain:75,w:{yes:{obstruction:34,arrhythmia:12},no:{obstruction:-12},unknown:{}}},
{id:'dbp',label:'DBP pattern',text:'Diastolic BP ต่ำเด่นเมื่อเทียบกับ systolic pattern หรือไม่?',why:'DBP ต่ำเด่นสนับสนุน low SVR/vasodilation แต่ต้องตีความร่วมกับ waveform และ context',opts:['yes','no','uncertain'],gain:62,w:{yes:{vasodilation:22},no:{vasodilation:-4},uncertain:{}}}
];
const INTERVENTIONS={
 AF_UNSTABLE:[['Synchronized cardioversion pathway','ใช้ local perioperative/ACLS protocol และ clinician judgement','cardioversion']],
 AF_STABLE:[['Treat reversible triggers','ทบทวน hypovolemia, hypoxia, pain, electrolytes และ anesthetic depth','triggers'],['Rate-control pathway','เลือกยา/ขนาดตาม patient factors และ local protocol','rate_control']],
 HEMORRHAGE:[['Control source + restore circulation','แจ้ง surgical team, ประเมิน blood loss และให้ resuscitation ตามบริบท','volume_source']],
 VASODILATION:[['Reduce anesthetic effect + support SVR','ทบทวน anesthetic depth/drugs และให้ hemodynamic support ตามบริบท','svr_support']],
 ANAPHYLAXIS:[['Activate anaphylaxis pathway','หยุด suspected trigger, call for help และใช้ local anaphylaxis protocol','anaphylaxis_path']],
 OBSTRUCTION:[['Evaluate obstructive physiology','ตรวจ circuit/airway และพิจารณา PE/tension physiology ตามบริบท','obstruction_path']]
};
let S={answers:{},actions:{},timeline:[],context:{phase:'maintenance',surgery:'general',risk:'none'},intervention:null,response:null,responseHistory:[]};
const $=q=>document.querySelector(q); const now=()=>new Date().toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit',second:'2-digit'});
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(S))} function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE_KEY));if(x)S={...S,...x}}catch(e){}}
function log(text,impact=''){S.timeline.unshift({time:now(),text,impact});save()}
function score(){const r={};Object.entries(CAUSES).forEach(([id,c])=>r[id]=c.base);for(const q of QUESTIONS){const a=S.answers[q.id];if(!a)continue;Object.entries((q.w&&q.w[a])||{}).forEach(([id,d])=>r[id]+=d)}
 if(S.context.phase==='induction')r.vasodilation+=10;if(S.context.surgery==='major_bleeding')r.hemorrhage+=12;if(S.context.risk==='cardiac')r.arrhythmia+=8;if(S.context.risk==='allergy')r.anaphylaxis+=8;
 const latest=S.responseHistory&&S.responseHistory.length?S.responseHistory[S.responseHistory.length-1].response:S.response; const m={map_hr_improved:{arrhythmia:12},hr_down_map_low:{arrhythmia:-18,vasodilation:18,hemorrhage:12},map_improved_hr_same:{vasodilation:8},no_change:{vasodilation:7,hemorrhage:9},worse:{hemorrhage:8,obstruction:9,arrhythmia:7}}[latest];if(m)Object.entries(m).forEach(([id,d])=>r[id]+=d);Object.keys(r).forEach(k=>r[k]=Math.max(1,Math.min(99,r[k])));return r}
function ranked(){return Object.entries(score()).sort((a,b)=>b[1]-a[1])}
function visible(q){return !q.show||q.show(S)}
function nextQuestion(){const sc=score();const unanswered=QUESTIONS.filter(q=>visible(q)&&!S.answers[q.id]);if(!unanswered.length)return null;return unanswered.map(q=>{let bonus=0;if(q.id==='bleeding'&&sc.hemorrhage>=sc.vasodilation-8)bonus+=20;if(q.id==='rhythmType'||q.id==='afStability')bonus+=30;if(q.id==='rash'&&sc.anaphylaxis>20)bonus+=15;if(q.id==='ppv'&&S.answers.bleeding==='unknown')bonus+=10;return{q,v:q.gain+bonus}}).sort((a,b)=>b.v-a.v)[0].q}
function evidenceFor(id){const lines=[];for(const q of QUESTIONS){const a=S.answers[q.id];if(!a)continue;const d=((q.w||{})[a]||{})[id]||0;if(d>0)lines.push(`${q.label}: ${a}`)}const latest=S.responseHistory&&S.responseHistory.length?S.responseHistory[S.responseHistory.length-1].response:S.response;if(latest){const map={arrhythmia:{map_hr_improved:'MAP/HR improved after rhythm intervention'},hemorrhage:{hr_down_map_low:'HR decreased but MAP remained low',no_change:'No meaningful response'},vasodilation:{hr_down_map_low:'HR improved but MAP remained low',map_improved_hr_same:'MAP improved while HR unchanged'},obstruction:{worse:'Instability worsened'},anaphylaxis:{}};const t=map[id]&&map[id][latest];if(t)lines.push(t)}return lines}
function evidenceAgainst(id){const lines=[];for(const q of QUESTIONS){const a=S.answers[q.id];if(!a)continue;const d=((q.w||{})[a]||{})[id]||0;if(d<0)lines.push(`${q.label}: ${a}`)}return lines}
function confidence(){const r=ranked();const gap=r[0][1]-r[1][1],n=Object.keys(S.answers).length;if(n<2)return'Low confidence';if(gap>=22&&n>=4)return'High confidence';return'Moderate confidence'}
function branch(){if(S.answers.rhythmType==='AF')return S.answers.afStability==='unstable'?'AF_UNSTABLE':'AF_STABLE';const top=ranked()[0][0];return({hemorrhage:'HEMORRHAGE',vasodilation:'VASODILATION',anaphylaxis:'ANAPHYLAXIS',obstruction:'OBSTRUCTION',arrhythmia:'AF_STABLE'})[top]}
function renderContext(){const c=S.context;$('#contextSummary').innerHTML=[c.phase,c.surgery,c.risk].map(x=>`<span class="chip">${x}</span>`).join('');$('#contextPanel').innerHTML=`<div class="contextGrid"><div class="contextGroup"><label>Phase</label><select data-k="phase"><option>induction</option><option>maintenance</option><option>emergence</option><option>PACU</option></select></div><div class="contextGroup"><label>Surgery context</label><select data-k="surgery"><option value="general">general</option><option value="major_bleeding">major bleeding potential</option><option value="laparoscopy">laparoscopy</option><option value="obstetric">obstetric</option><option value="prone">prone</option></select></div><div class="contextGroup"><label>Patient factor</label><select data-k="risk"><option value="none">none selected</option><option value="cardiac">cardiac disease</option><option value="allergy">allergy risk</option><option value="extreme_age">extreme age</option><option value="pulmonary">asthma/COPD</option></select></div></div>`;document.querySelectorAll('#contextPanel select').forEach(el=>{el.value=c[el.dataset.k];el.onchange=()=>{S.context[el.dataset.k]=el.value;log(`Context: ${el.dataset.k} = ${el.value}`,'Working probabilities updated');render()}})}
function renderPriority(){const [id,val]=ranked()[0];$('#confidencePill').textContent=confidence();let title='Treat hypotension now',text='Stabilize first while collecting the smallest amount of information that changes management.';if(id==='hemorrhage'){title='Control bleeding and restore circulation';text='Current evidence favors hemorrhage/hypovolemia. Confirm source and adequacy of resuscitation.'}if(id==='vasodilation'){title='Support circulation and reduce reversible vasodilation';text='Review anesthetic depth, recent drugs, DBP pattern and response to support.'}if(id==='arrhythmia'){title='Clarify rhythm and hemodynamic impact';text='Do not stop at “pump failure”; identify rhythm, stability and response.'}if(id==='anaphylaxis'){title='Treat possible anaphylaxis immediately';text='Escalate using local protocol while confirming airway/skin/circulatory signs.'}if(id==='obstruction'){title='Exclude abrupt obstructive physiology';text='Reassess airway, ventilation and pulmonary blood-flow clues immediately.'}$('#priorityTitle').textContent=title;$('#priorityText').textContent=text;const nq=nextQuestion();$('#mentorCue').textContent=nq?`อาจารย์แนะนำ: ตอนนี้ ${CAUSES[id].name} นำอยู่ (${val}). คำถามถัดไปถูกเลือกเพราะจะเปลี่ยนการรักษาได้มากที่สุด ไม่ใช่เพราะอยู่ลำดับถัดไปใน checklist.`:'ข้อมูลสำคัญหลักครบแล้ว ให้เลือก intervention และประเมิน response เพื่อปรับ working diagnosis ต่อ'}
function renderActions(){const b=$('#actions');b.innerHTML='';ACTIONS.forEach((x,i)=>{const bt=document.createElement('button');bt.className='action'+(S.actions[i]?' done':'');bt.textContent=x;bt.onclick=()=>{S.actions[i]=!S.actions[i];log(`${x}: ${S.actions[i]?'done':'reopened'}`);render()};b.appendChild(bt)})}
function renderQuestion(){const q=nextQuestion(),card=$('#questionCard');card.classList.toggle('hidden',!q);if(!q)return;$('#questionMeta').textContent=`Info value ${q.gain}`;$('#questionWhy').textContent=`Why this now: ${q.why}`;$('#questionText').textContent=q.text;const b=$('#questionOptions');b.innerHTML='';q.opts.forEach(v=>{const bt=document.createElement('button');bt.className='option';bt.textContent=v;bt.onclick=()=>{S.answers[q.id]=v;S.response=null;log(`${q.label}: ${v}`,'Working diagnosis re-ranked');render()};b.appendChild(bt)})}
function renderIntervention(){const options=INTERVENTIONS[branch()]||[],card=$('#interventionCard');const ready=Object.keys(S.answers).length>=2||!nextQuestion();card.classList.toggle('hidden',!ready);if(!ready)return;$('#interventionTitle').textContent='เลือกการกระทำที่เหมาะกับ working diagnosis';$('#interventionDetail').textContent='Prototype จะแสดงแนวทางระดับ pathway ไม่แนะนำ dose เฉพาะราย';const b=$('#interventionOptions');b.innerHTML='';options.forEach(([t,d,id])=>{const bt=document.createElement('button');bt.className='interventionBtn';bt.innerHTML=`<strong>${t}</strong><small>${d}</small>`;bt.onclick=()=>{S.intervention={id,title:t,detail:d,given:true,startedAt:now()};S.response=null;log(`Intervention: ${t}`,'Awaiting physiologic response');render()};b.appendChild(bt)})}
function renderResponse(){const card=$('#responseCard'),show=!!S.intervention&&!S.response;card.classList.toggle('hidden',!show);if(!show)return;$('#responseQuestion').textContent=`หลัง “${S.intervention.title}” ผู้ป่วยตอบสนองอย่างไร?`;const opts=[['map_hr_improved','MAP และ HR ดีขึ้น','สนับสนุนว่า intervention จัดการ contributor สำคัญ'],['hr_down_map_low','HR ลด แต่ MAP ยังต่ำ','arrhythmia อาจไม่ใช่สาเหตุหลัก'],['map_improved_hr_same','MAP ดีขึ้น แต่ HR ไม่เปลี่ยน','ยังต้องหาสาเหตุ tachycardia ต่อ'],['no_change','ไม่เปลี่ยนชัดเจน','ทบทวน diagnosis, adequacy และ alternative causes'],['worse','แย่ลง / instability เพิ่ม','Escalate และ reassess reversible causes ทันที']];const b=$('#responseOptions');b.innerHTML='';opts.forEach(([id,t,d])=>{const bt=document.createElement('button');bt.className='response';bt.innerHTML=`<strong>${t}</strong><small>${d}</small>`;bt.onclick=()=>{S.response=id;S.responseHistory=S.responseHistory||[];S.responseHistory.push({time:now(),intervention:S.intervention.title,response:id,label:t});log(`Response: ${t}`,'Response fed back into working diagnosis; next cycle opened');S.intervention=null;S.response=null;render()};b.appendChild(bt)})}
function renderCauses(){const b=$('#causes');b.innerHTML='';ranked().forEach(([id,v],idx)=>{const f=evidenceFor(id).length,a=evidenceAgainst(id).length;const d=document.createElement('div');d.className='cause';d.innerHTML=`<div class="causeHead"><b>${idx===0?'★ ':''}${CAUSES[id].name}</b><span>${v}</span></div><div class="causeSub">${f} supporting • ${a} against</div><div class="bar"><span style="width:${v}%"></span></div>`;b.appendChild(d)})}
function renderEvidence(){const b=$('#evidence');b.innerHTML='';ranked().slice(0,3).forEach(([id])=>{const f=evidenceFor(id),a=evidenceAgainst(id);const d=document.createElement('div');d.className='evidenceBlock';d.innerHTML=`<div class="evidenceTitle">${CAUSES[id].name}</div><div class="evidenceLine for">Supporting: ${f.length?f.join(' • '):'ยังไม่มีหลักฐานจำเพาะ'}</div><div class="evidenceLine against">Against: ${a.length?a.join(' • '):'ยังไม่มีหลักฐานค้านชัดเจน'}</div>`;b.appendChild(d)})}
function renderAnswers(){const b=$('#answers');b.innerHTML='';const qs=QUESTIONS.filter(q=>S.answers[q.id]);if(!qs.length){b.innerHTML='<div class="small">No answers yet.</div>';return}qs.forEach(q=>{const bt=document.createElement('button');bt.className='answer';bt.innerHTML=`<span>${q.label}</span><b>${S.answers[q.id]} ›</b>`;bt.onclick=()=>openEdit(q);b.appendChild(bt)});(S.responseHistory||[]).slice().reverse().forEach(x=>{const d=document.createElement('div');d.className='answer responseHistory';d.innerHTML=`<span>${x.intervention}</span><b>${x.label}</b>`;b.appendChild(d)})}
function openEdit(q){$('#editSheet').classList.remove('hidden');$('#editTitle').textContent=q.text;const b=$('#editOptions');b.innerHTML='';q.opts.forEach(v=>{const bt=document.createElement('button');bt.className='option';bt.textContent=v;bt.onclick=()=>{const old=S.answers[q.id];S.answers[q.id]=v;S.response=null;log(`${q.label}: corrected ${old} → ${v}`,'Downstream reasoning recalculated');$('#editSheet').classList.add('hidden');render()};b.appendChild(bt)})}
function renderTimeline(){const b=$('#timeline');b.innerHTML=S.timeline.length?'':'<div class="small">Timeline appears automatically.</div>';S.timeline.forEach(x=>{const d=document.createElement('div');d.className='tItem';d.innerHTML=`<time>${x.time}</time><div>${x.text}${x.impact?`<span class="impact">↳ ${x.impact}</span>`:''}</div>`;b.appendChild(d)})}
function render(){renderContext();renderPriority();renderActions();renderQuestion();renderIntervention();renderResponse();renderCauses();renderEvidence();renderAnswers();renderTimeline();save()}
$('#contextToggle').onclick=()=>$('#contextPanel').classList.toggle('hidden');$('#cancelEdit').onclick=()=>$('#editSheet').classList.add('hidden');$('#editSheet').onclick=e=>{if(e.target.id==='editSheet')$('#editSheet').classList.add('hidden')};$('#resetBtn').onclick=()=>{if(confirm('Reset case?')){S={answers:{},actions:{},timeline:[],context:{phase:'maintenance',surgery:'general',risk:'none'},intervention:null,response:null,responseHistory:[]};render()}};load();render();
