/* Anesthculator v0.34 Cloud — library/reference data only; no patient fields are sent. */
(()=>{
const SUPABASE_URL='https://uktfoqvmkxfpczbbmepy.supabase.co';
const SUPABASE_KEY='sb_publishable_A2NLYpy1dt1D30lwa_S3bg_656DfnPH';
const SESSION_KEY='anesthCloudSessionV033';
const $c=id=>document.getElementById(id);
let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null');
const token=()=>session?.access_token||null;
function headers(extra={}){return {'apikey':SUPABASE_KEY,'Authorization':`Bearer ${token()||SUPABASE_KEY}`,'Content-Type':'application/json',...extra}}
async function api(path,opt={}){let r=await fetch(SUPABASE_URL+path,{...opt,headers:headers(opt.headers||{})});let text=await r.text();let data;try{data=text?JSON.parse(text):null}catch{data=text}if(!r.ok)throw new Error(data?.message||data?.msg||data?.error_description||data?.error||`${r.status} ${r.statusText}`);return data}
function setMsg(m){if($c('cloudSyncText'))$c('cloudSyncText').textContent=m}
function authUI(){let on=!!token();$c('cloudStatus').textContent=on?'Connected':'Signed out';$c('cloudUserText').textContent=on?`${session.user?.email||'Signed in'} • role loaded from profile on refresh`:'Sign in to use the shared Drug Library.';$c('cloudSignOut').hidden=!on;$c('cloudSignIn').hidden=on;$c('cloudSignUp').hidden=on}
async function signIn(){try{let email=$c('cloudEmail').value.trim(),password=$c('cloudPassword').value;session=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});localStorage.setItem(SESSION_KEY,JSON.stringify(session));authUI();await refresh()}catch(e){alert('Sign in failed: '+e.message)}}
async function signUp(){try{let email=$c('cloudEmail').value.trim(),password=$c('cloudPassword').value;let x=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(x?.access_token){session=x;localStorage.setItem(SESSION_KEY,JSON.stringify(x));authUI();await refresh()}else alert('Account created. Check your email if confirmation is enabled, then sign in.')}catch(e){alert('Create account failed: '+e.message)}}
function signOut(){session=null;localStorage.removeItem(SESSION_KEY);window.setCloudLibrary?.([]);authUI();setMsg('Signed out. Built-in and local libraries remain available.')}
function mapCloud(drugs,doses){let by={};for(let x of doses||[])(by[x.drug_id]??=[]).push(x);return (drugs||[]).map(d=>{let rs=by[d.id]||[];let r=rs[0]||{};return {id:'cloud-'+d.id,cloudId:d.id,name:d.generic_name,displayName:d.display_name,category:d.primary_category||'Other',categories:[d.primary_category||'Other'],drugClass:d.drug_class||'',phase:r.phase||'Other',phases:[...new Set(rs.map(x=>x.phase).filter(Boolean))],context:r.indication||'',min:r.dose_min,max:r.dose_max,def:r.dose_default,unit:r.dose_unit,stock:r.stock_concentration,stockUnit:r.stock_unit,ref:'Cloud Library • '+(r.status||'dose_locked'),doseLocked:r.status==='dose_locked',checked:['source_verified','local_verified'].includes(r.status),verification:(r.status||'').toUpperCase(),dosingRecords:rs.map(x=>({phase:x.phase||'Other',context:x.indication||'',min:x.dose_min,max:x.dose_max,def:x.dose_default,unit:x.dose_unit,stock:x.stock_concentration,stockUnit:x.stock_unit,ref:'Cloud • '+x.status,route:x.route,population:x.population}))}})}
async function refresh(){if(!token()){setMsg('Sign in first.');return}try{setMsg('Syncing…');let [drugs,doses,profile]=await Promise.all([api('/rest/v1/drugs?select=*&active=eq.true&order=generic_name.asc'),api('/rest/v1/dose_records?select=*&order=created_at.asc'),api('/rest/v1/profiles?select=id,display_name,role&id=eq.'+encodeURIComponent(session.user.id))]);window.setCloudLibrary?.(mapCloud(drugs,doses));let role=profile?.[0]?.role||'viewer';$c('cloudStatus').textContent='Connected • '+role;$c('cloudUserText').textContent=`${session.user.email} • ${role}`;setMsg(`Cloud ready: ${drugs.length} drug(s), ${doses.length} dose record(s).`)}catch(e){setMsg('Sync failed: '+e.message)}}
async function saveReference(){if(!token()){alert('Sign in first.');return}let title=$c('refTitle').value.trim();if(!title){alert('Reference title is required.');return}try{$c('refCloudResult').textContent='Saving…';let body={title,organization:$c('refOrg').value||null,edition:$c('refEdition').value||null,publication_date:$c('refDate').value||null,page_reference:$c('refPage').value||null,table_reference:$c('refTable').value||null,section_reference:$c('refSection').value||null,url:$c('refUrl').value||null,notes:$c('refNotes').value||null,source_type:$c('refType').value,created_by:session.user.id};let refs=await api('/rest/v1/references',{method:'POST',headers:{'Prefer':'return=representation'},body:JSON.stringify(body)});let ref=refs[0],file=$c('refFile').files?.[0];if(file){let safe=(file.name||'evidence').replace(/[^a-zA-Z0-9._-]/g,'_');let path=`${ref.id}/${crypto.randomUUID()}-${safe}`;let r=await fetch(`${SUPABASE_URL}/storage/v1/object/reference-files/${path}`,{method:'POST',headers:{'apikey':SUPABASE_KEY,'Authorization':`Bearer ${token()}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:file});if(!r.ok)throw new Error('Reference saved, but evidence upload failed: '+await r.text());await api('/rest/v1/reference_files',{method:'POST',body:JSON.stringify({reference_id:ref.id,storage_path:path,original_filename:file.name,mime_type:file.type||null,uploaded_by:session.user.id,file_size_bytes:file.size})})}$c('refCloudResult').textContent='Saved to cloud successfully.'}catch(e){$c('refCloudResult').textContent='Save failed: '+e.message}}
$c('cloudSignIn').onclick=signIn;$c('cloudSignUp').onclick=signUp;$c('cloudSignOut').onclick=signOut;$c('cloudRefresh').onclick=refresh;$c('saveReferenceCloud').onclick=saveReference;authUI();if(token())refresh();
})();
